# Pre-commit hooks for Claude Code Agents Pipeline
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Prevent large files from being committed
      - id: check-added-large-files
        args: ['--maxkb=500']

      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict

      # Ensure files end with newline
      - id: end-of-file-fixer
        exclude: \.svg$

      # Trim trailing whitespace
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      # Check YAML syntax
      - id: check-yaml
        args: ['--unsafe']  # Allow custom tags

      # Check JSON syntax
      - id: check-json

      # Prevent committing to main branch
      - id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'master']

      # Check for merge conflicts
      - id: check-merge-conflict

      # Detect private keys
      - id: detect-private-key

      # Check for AWS credentials
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']

      # Fix mixed line endings
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Shellcheck for bash scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: ['-x', '-e', 'SC1091']  # -x: follow sources, -e: exclude SC1091 (can't follow source)
        files: \.(sh|bash)$
        types: [shell]

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        files: \.md$
        exclude: ^(CHANGELOG\.md|\.github/)

  # JSON validation and formatting
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.0
    hooks:
      - id: check-jsonschema
        name: Validate state.json schema
        files: state\.json$
        args: ['--schemafile', '.github/schemas/state-schema.json']
        # Validates pipeline state file against JSON Schema draft-07

      - id: check-jsonschema
        name: Validate package.json
        files: package\.json$
        args: ['--builtin-schema', 'vendor.package']

  # Commit message validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock\.json

  # Python code quality (for any Python scripts)
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3
        files: \.py$

  # YAML formatting
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.11.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix, --indent, '2']
        files: \.ya?ml$
        exclude: ^(\.github/workflows/)

# Global configuration
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: 3.0.0
