name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  test:
    name: Test Before Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Run tests
      run: |
        chmod +x tests/run_all_tests.sh
        bash tests/run_all_tests.sh

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Generate changelog
      id: changelog
      run: |
        # Get previous tag
        PREV_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")

        if [ -z "$PREV_TAG" ]; then
          # First release - get all commits
          COMMITS=$(git log --pretty=format:"- %s (%h)" --reverse)
        else
          # Get commits since last tag
          COMMITS=$(git log ${PREV_TAG}..HEAD --pretty=format:"- %s (%h)" --reverse)
        fi

        # Save to file
        echo "## What's Changed" > CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "$COMMITS" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/${PREV_TAG}...${{ steps.get_version.outputs.VERSION }}" >> CHANGELOG.md

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
        files: |
          pipeline.sh
          install.sh
          quickstart.sh
          README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Publish to NPM (Future)
    runs-on: ubuntu-latest
    needs: create-release
    if: false  # Disabled until package.json is created

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-homebrew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    needs: create-release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Get release URL and SHA256
      id: get_release_info
      run: |
        # Get tarball URL
        TARBALL_URL="https://github.com/${{ github.repository }}/archive/${{ steps.get_version.outputs.TAG }}.tar.gz"
        echo "TARBALL_URL=$TARBALL_URL" >> $GITHUB_OUTPUT

        # Download and calculate SHA256
        curl -sL "$TARBALL_URL" -o release.tar.gz
        SHA256=$(sha256sum release.tar.gz | awk '{print $1}')
        echo "SHA256=$SHA256" >> $GITHUB_OUTPUT
        echo "SHA256: $SHA256"

    - name: Update Homebrew tap
      env:
        HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
      run: |
        # Clone homebrew tap repository
        git clone https://github.com/${{ github.repository_owner }}/homebrew-tap.git tap
        cd tap

        # Configure git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Update formula
        cat > Formula/claude-code-agents.rb << 'EOF'
        class ClaudeCodeAgents < Formula
          desc "BDD-driven development pipeline with Claude Code integration"
          homepage "https://github.com/${{ github.repository }}"
          url "${{ steps.get_release_info.outputs.TARBALL_URL }}"
          sha256 "${{ steps.get_release_info.outputs.SHA256 }}"
          version "${{ steps.get_version.outputs.VERSION }}"
          license "MIT"

          depends_on "jq"
          depends_on "git"

          def install
            bin.install "pipeline.sh" => "pipeline"
            prefix.install "README.md"
            prefix.install Dir["docs/*"]
          end

          test do
            system "#{bin}/pipeline", "--version"
          end
        end
        EOF

        # Commit and push
        git add Formula/claude-code-agents.rb
        git commit -m "Update claude-code-agents to ${{ steps.get_version.outputs.VERSION }}"
        git push https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/${{ github.repository_owner }}/homebrew-tap.git main
